export const pagesRoutes = [
  ["v-4bbfdb41","/11111.html",{"title":"主页","icon":"home"},["/11111","/11111.md"]],
  ["v-8daa1a0e","/",{"title":"主页","icon":"home"},["/index.html","/README.md"]],
  ["v-2e3eac9e","/slides.html",{"title":"幻灯片页","icon":"slides"},["/slides","/slides.md"]],
  ["v-339f4508","/contents/",{"title":"主要功能与配置演示","icon":"creative"},["/contents/index.html","/contents/README.md"]],
  ["v-0188b26d","/contents/disable.html",{"title":"布局与功能禁用","icon":"config"},["/contents/disable","/contents/disable.md"]],
  ["v-6fda6de0","/contents/encrypt.html",{"title":"密码加密的文章","icon":"lock"},["/contents/encrypt","/contents/encrypt.md"]],
  ["v-661d2564","/contents/markdown.html",{"title":"Markdown 展示","icon":"markdown"},["/contents/markdown","/contents/markdown.md"]],
  ["v-43722dae","/contents/page.html",{"title":"页面配置","icon":"page"},["/contents/page","/contents/page.md"]],
  ["v-fffb8e28","/guide/",{"title":"指南","icon":"creative"},["/guide/index.html","/guide/README.md"]],
  ["v-6870da79","/docs/design-pattren/",{"title":""},["/docs/design-pattren/index.html","/docs/design-pattren/README.md"]],
  ["v-67aa0d9c","/docs/java/",{"title":""},["/docs/java/index.html","/docs/java/README.md"]],
  ["v-6a7e50b8","/docs/raspberry-pi/",{"title":"树莓派小记","icon":"router"},["/docs/raspberry-pi/index.html","/docs/raspberry-pi/README.md"]],
  ["v-2fe617e4","/docs/vue/",{"title":"Vue小记","icon":"vue"},["/docs/vue/index.html","/docs/vue/README.md"]],
  ["v-5d5c2d30","/guide/bar/",{"title":"Bar 功能","icon":"creative"},["/guide/bar/index.html","/guide/bar/README.md"]],
  ["v-177e1f06","/guide/bar/baz.html",{"title":"Baz","icon":"info"},["/guide/bar/baz","/guide/bar/baz.md"]],
  ["v-5d5821d6","/guide/foo/",{"title":"Foo 功能","icon":"config"},["/guide/foo/index.html","/guide/foo/README.md"]],
  ["v-0b6fc5f8","/guide/foo/ray.html",{"title":"Ray","icon":"config"},["/guide/foo/ray","/guide/foo/ray.md"]],
  ["v-2a9c9c65","/docs/java/collections/List2Map.html",{"title":"List转Map","icon":"workingDirectory"},["/docs/java/collections/List2Map","/docs/java/collections/List2Map.md"]],
  ["v-45994b6c","/docs/java/collections/",{"title":"Collections集合","icon":"workingDirectory"},["/docs/java/collections/index.html","/docs/java/collections/README.md"]],
  ["v-21eb6986","/docs/java/stream/",{"title":"Stream流","icon":"footnote"},["/docs/java/stream/index.html","/docs/java/stream/README.md"]],
  ["v-7f1fa930","/docs/raspberry-pi/preparation/",{"title":"准备工作","icon":"router"},["/docs/raspberry-pi/preparation/index.html","/docs/raspberry-pi/preparation/README.md"]],
  ["v-3af08c12","/docs/raspberry-pi/preparation/boot.html",{"title":"首次开机","icon":"router"},["/docs/raspberry-pi/preparation/boot","/docs/raspberry-pi/preparation/boot.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
  ["v-659f9a5a","/docs/raspberry-pi/preparation/configuration.html",{"title":"系统配置","icon":"router"},["/docs/raspberry-pi/preparation/configuration","/docs/raspberry-pi/preparation/configuration.md"]],
]
